const DATE_FORMAT = 'YYYY-MM-DD'
const YEAR_FORMAT = 'YYYY'
const MONTH_FORMAT = 'M'
const DAY_WITH_MONTH_FORMAT = 'D MMMM'
const TIME_FORMAT = 'H:mm'
const LONG_MONTH_FORMAT = 'MMMM'
const LONG_DAY_FORMAT = 'dddd'

const CALENDAR_HEADERS = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд']

export {
  CALENDAR_HEADERS,
  DATE_FORMAT,
  DAY_WITH_MONTH_FORMAT,
  LONG_DAY_FORMAT,
  LONG_MONTH_FORMAT,
  MONTH_FORMAT,
  TIME_FORMAT,
  YEAR_FORMAT
}
