const GROUPS_QUERY_KEY = 'groups'
const AUDITORIUMS_QUERY_KEY = 'auditoriums'
const TEACHERS_QUERY_KEY = 'teachers'
const SCHEDULE_QUERY_KEY = 'schedule'

export { GROUPS_QUERY_KEY, AUDITORIUMS_QUERY_KEY, TEACHERS_QUERY_KEY, SCHEDULE_QUERY_KEY }
